In [3]:
import pandas as pd
df = pd.read_csv('pokemon_data.csv')
print(df.head(3))
print(df.tail(3))

   #       Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  \
0  1  Bulbasaur  Grass  Poison  45      49       49       65       65     45
1  2    Ivysaur  Grass  Poison  60      62       63       80       80     60
2  3   Venusaur  Grass  Poison  80      82       83      100      100     80

   Generation  Legendary
0           1      False
1           1      False
2           1      False
       #                 Name   Type 1 Type 2  HP  Attack  Defense  Sp. Atk  \
797  720  HoopaHoopa Confined  Psychic  Ghost  80     110       60      150
798  720   HoopaHoopa Unbound  Psychic   Dark  80     160       60      170
799  721            Volcanion     Fire  Water  80     110      120      130

     Sp. Def  Speed  Generation  Legendary
797      130     70           6       True
798      130     80           6       True
799       90     70           6       True

### READING DATA IN PANDAS

In [14]:
#PRINT HEADER 
#print(df.columns)

#READ EACH COLUMN 
#print(df[['Name','Defense']])

#READ EACH ROW 
#print(df.iloc[0:4])

#READ A SPECIFIC LOCATION
#print(df.iloc[0,1

#IF WE WANNA DO ITTER ROWS
#for index, row in df. iterrows():
    #print(index,row["Name"])

#TO FIND SOMETHING IN THE WHOLE DATASET
df.loc[df['Type 1'] == "Fire"]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,False
42,37,Vulpix,Fire,NaN,38,41,40,50,65,65,1,False
43,38,Ninetales,Fire,NaN,73,76,75,81,100,100,1,False
63,58,Growlithe,Fire,NaN,55,70,45,70,50,60,1,False
64,59,Arcanine,Fire,NaN,90,110,80,100,80,95,1,False
83,77,Ponyta,Fire,NaN,50,85,55,65,65,90,1,False
84,78,Rapidash,Fire,NaN,65,100,70,80,80,105,1,False
135,126,Magmar,Fire,NaN,65,95,57,100,85,93,1,False
147,136,Flareon,Fire,NaN,65,130,60,95,110,65,1,False
158,146,Moltres,Fire,Flying,90,100,90,125,85,90,1,True
169,155,Cyndaquil,Fire,NaN,39,52,43,60,50,65,2,False
170,156,Quilava,Fire,NaN,58,64,58,80,65,80,2,False
171,157,Typhlosion,Fire,NaN,78,84,78,109,85,100,2,False
236,218,Slugma,Fire,NaN,40,40,40,70,40,20,2,False
237,219,Magcargo,Fire,Rock,50,50,120,80,80,30,2,False
259,240,Magby,Fire,NaN,45,75,37,70,55,83,2,False
263,244,Entei,Fire,NaN,115,115,85,90,75,100,2,True
270,250,Ho-oh,Fire,Flying,106,130,90,110,154,90,2,True
276,255,Torchic,Fire,NaN,45,60,40,70,50,45,3,False
277,256,Combusken,Fire,Fighting,60,85,60,85,60,55,3,False
278,257,Blaziken,Fire,Fighting,80,120,70,110,70,80,3,False
279,257,BlazikenMega Blaziken,Fire,Fighting,80,160,80,130,80,100,3,False
352,322,Numel,Fire,Ground,60,60,40,65,45,35,3,False
353,323,Camerupt,Fire,Ground,70,100,70,105,75,40,3,False
354,323,CameruptMega Camerupt,Fire,Ground,70,120,100,145,105,20,3,False
355,324,Torkoal,Fire,NaN,70,85,140,85,70,20,3,False
435,390,Chimchar,Fire,NaN,44,58,44,58,44,61,4,False
436,391,Monferno,Fire,Fighting,64,78,52,78,52,81,4,False
437,392,Infernape,Fire,Fighting,76,104,71,104,71,108,4,False
518,467,Magmortar,Fire,NaN,75,95,67,125,95,83,4,False
542,485,Heatran,Fire,Steel,91,90,106,130,106,77,4,True
557,498,Tepig,Fire,NaN,65,63,45,45,45,45,5,False
558,499,Pignite,Fire,Fighting,90,93,55,70,55,55,5,False
559,500,Emboar,Fire,Fighting,110,123,65,100,65,65,5,False
572,513,Pansear,Fire,NaN,50,53,48,53,48,64,5,False
573,514,Simisear,Fire,NaN,75,98,63,98,63,101,5,False
614,554,Darumaka,Fire,NaN,70,90,45,15,45,50,5,False
615,555,DarmanitanStandard Mode,Fire,NaN,105,140,55,30,55,95,5,False
616,555,DarmanitanZen Mode,Fire,Psychic,105,30,105,140,105,55,5,False
692,631,Heatmor,Fire,NaN,85,97,66,105,66,65,5,False
721,653,Fennekin,Fire,NaN,40,45,40,62,60,60,6,False
722,654,Braixen,Fire,NaN,59,59,58,90,70,73,6,False
723,655,Delphox,Fire,Psychic,75,69,72,114,100,104,6,False
730,662,Fletchinder,Fire,Flying,62,73,55,56,52,84,6,False
731,663,Talonflame,Fire,Flying,78,81,71,74,69,126,6,False
735,667,Litleo,Fire,Normal,62,50,58,73,54,72,6,False
736,668,Pyroar,Fire,Normal,86,68,72,109,66,106,6,False
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

### SORTING AND DESCRIBING DATA

In [17]:
#df.describe()
df.sort_values(['Type 1', 'HP'], ascending = False)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
351,321,Wailord,Water,NaN,170,90,45,90,45,60,3,False
655,594,Alomomola,Water,NaN,165,75,80,40,45,65,5,False
142,131,Lapras,Water,Ice,130,85,80,85,95,60,1,False
145,134,Vaporeon,Water,NaN,130,65,60,110,95,65,1,False
350,320,Wailmer,Water,NaN,130,70,35,70,35,60,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...
314,290,Nincada,Bug,Ground,31,45,90,30,30,40,3,False
462,415,Combee,Bug,Flying,30,30,42,30,42,70,4,False
603,543,Venipede,Bug,Poison,30,45,59,30,39,57,5,False
230,213,Shuckle,Bug,Rock,20,10,230,10,230,5,2,False
316,292,Shedinja,Bug,Ghost,1,90,45,30,30,40,3,False

### LET'S START MAKING CHANGES TO THE DATA

In [37]:
#THE BASIC METHOD
#df['TOATAL']= df['HP']+df['Attack']+df['Defense']+df['Sp. Atk']+df['Sp. Def']+df['Speed']
#df = df.drop(columns = ['TOATAL'])

#MOVE THE TOTAL COLUMN  TO  THE LEFT SIDE USING LIST AND STRINGS 
df['TOTAL'] = df.iloc[:, 4:10].sum(axis = 1)

#to bring a whole column in the front
cols = list(df.columns)
df = df[cols[0:3]+[cols [-1]]+ cols[4:12]]
df.head(5)
df.to_csv('modified.csv')

In [56]:
#new_data_frame = df.loc[(df["Type 1"]=='Bug') & (df['HP']>70)]
#WE CAN SAVE THIS AS A NEW CSV FILE AND PRINT IT OR WE CAN JUST PRINT DF WHICH IS THE ORIGINAL ONE
#new_data_frame = new_data_frame.reset_index(drop = True)
#new_data_frame
import re
#df.loc[df['Name'].str.contains('Mega'),regex = True
#df.loc[df['Type 1']== 'Fire','Legendary']= True       
df

,#,Name,Type 1,TOTAL,Legendary,Legendary,Legendary,Legendary,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
0,1,Bulbasaur,Grass,273,False,False,False,False,45,49,49,65,65,45,1
1,2,Ivysaur,Grass,345,False,False,False,False,60,62,63,80,80,60,1
2,3,Venusaur,Grass,445,False,False,False,False,80,82,83,100,100,80,1
3,3,VenusaurMega Venusaur,Grass,545,False,False,False,False,80,100,123,122,120,80,1
4,4,Charmander,Fire,244,True,True,True,True,39,52,43,60,50,65,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,551,True,True,True,True,50,100,150,100,150,50,6
796,719,DiancieMega Diancie,Rock,591,True,True,True,True,50,160,110,160,110,110,6
797,720,HoopaHoopa Confined,Psychic,531,True,True,True,True,80,110,60,150,130,70,6
798,720,HoopaHoopa Unbound,Psychic,601,True,True,True,True,80,160,60,170,130,80,6
799,721,Volcanion,Fire,531,True,True,True,True,80,110,120,130,90,70,6